### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jacky09299** [WingSyncAlgorithm/Practice#19]
@WingSync **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jacky09299** [comment]
1

**Comment by WingSync** [comment]
1

jacky09299 ***@***.***> 於 2023年12月1日 週五 上午1:56寫道：

**Comment by jacky09299** [comment]
2

WingSync ***@***.***>於 2023年12月1日 週五，上午3:04寫道：
