### ISSUE TITLE
1

### ISSUE THREAD

**Issue by jacky09299** [WingSyncAlgorithm/Practice#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by WingSync** [comment]
1

**Comment by jacky09299** [comment]
1

WingSync ***@***.***>於 2023年12月20日 週三，下午4:57寫道：

**Comment by WingSync** [comment]
1

jacky09299 ***@***.***> 於 2023年12月20日 週三 下午5:00寫道：
